<a href="https://colab.research.google.com/github/BrendaChepkoech/Moringa-Week-4-IP/blob/main/Brenda_Chepkoech_week_4_IP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.0 Importing our Libraries

In [1]:
# Importing the libraries we will need 

# Importing the pandas library
# 
import pandas as pd

# Importing the numpy library
#
import numpy as np

# 1.1 Reading the Dataset from our CSV file


The dataset we will use contains data collected for electric car usage over a period of 9 days 

*    Dataset link for download or access ; http://bit.ly/autolib_dataset




In [2]:
# Let's read the data from the CSV file and create the dataframe to be used
df= pd.read_csv("Autolib_dataset.csv")

# 1.2 Previewing our dataset

In [3]:
# Let's preview the first 5 rows of our data
# 
df.head(5)

Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue Eugène Oudiné     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

# 1.3 Accessing Information about our Dataset

In [4]:
# Getting to know more about the dataset by accessing its information
# 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64 
 2   Bluecar counter      5000 non-null   int64 
 3   Utilib counter       5000 non-null   int64 
 4   Utilib 1.4 counter   5000 non-null   int64 
 5   Charge Slots         5000 non-null   int64 
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64 
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots 

# 1.4 Cleaning our Dataset

In [5]:
#Dropping the irrelevant colums
df.drop(['Charge Slots','Charging Status','Rental status','Slots','Cars','Displayed comment','Geo point','Scheduled at','ID'],axis=1,inplace=True)


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Address              5000 non-null   object
 1   Bluecar counter      5000 non-null   int64 
 2   Utilib counter       5000 non-null   int64 
 3   Utilib 1.4 counter   5000 non-null   int64 
 4   City                 5000 non-null   object
 5   Kind                 5000 non-null   object
 6   Postal code          5000 non-null   int64 
 7   Public name          5000 non-null   object
 8   Station type         5000 non-null   object
 9   Status               5000 non-null   object
 10  Subscription status  5000 non-null   object
 11  year                 5000 non-null   int64 
 12  month                5000 non-null   int64 
 13  day                  5000 non-null   int64 
 14  hour                 5000 non-null   int64 
 15  minute               5000 non-null   int64 
dtypes: int

In [7]:
# check for columns with non values 
#No null values
df.notnull()

Address  Bluecar counter  Utilib counter  ...   day  hour  minute
0        True             True            True  ...  True  True    True
1        True             True            True  ...  True  True    True
2        True             True            True  ...  True  True    True
3        True             True            True  ...  True  True    True
4        True             True            True  ...  True  True    True
...       ...              ...             ...  ...   ...   ...     ...
4995     True             True            True  ...  True  True    True
4996     True             True            True  ...  True  True    True
4997     True             True            True  ...  True  True    True
4998     True             True            True  ...  True  True    True
4999     True             True            True  ...  True  True    True

[5000 rows x 16 columns]

In [8]:
#Lets drop the null colums and rows
df.dropna(axis=1)
df.dropna

<bound method DataFrame.dropna of                                  Address  Bluecar counter  ...  hour  minute
0                    2 Avenue de Suffren                0  ...    11      43
1              145 Rue Raymond Losserand                6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy                3  ...    20      14
3                 51 Rue Eugène Oudiné                3  ...     4      37
4     6 avenue de la Porte de Champerret                3  ...    17      23
...                                  ...              ...  ...   ...     ...
4995                 8 avenue Ménelotte                2  ...    11      26
4996                   37 rue de Dantzig                4  ...    16      56
4997                      142 rue du Bac                1  ...     7       1
4998         2 avenue du Val de Fontenay                2  ...    17      27
4999                 5 Rue Henry Brisson                4  ...    10       2

[5000 rows x 16 columns]>

In [9]:
#checking for duplicates
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [10]:
#dropping duplicates
df=df.drop_duplicates()

In [11]:
#Changing the case of column names to lower, stripping whitespaces, 
#removing periods and replacing spaces with underscore

df.columns = df.columns.str.lower().str.strip().str.replace(' ', '_').str.replace('.', '')
df.columns

Index(['address', 'bluecar_counter', 'utilib_counter', 'utilib_14_counter',
       'city', 'kind', 'postal_code', 'public_name', 'station_type', 'status',
       'subscription_status', 'year', 'month', 'day', 'hour', 'minute'],
      dtype='object')

In [12]:
#Adding a usage column for the three car counters (bluecar_counter, utilib_counter and utilib_14_counter)
#+ve number means that a car was returned, -ve number means that a car was picked 
#0 means that nothing happened, i.e no car was picked nor returned

#Creating column for bluecar usage
df['bluecar_usage'] = df.bluecar_counter.diff()

#Creating column for utilib usage
df['utilib_usage'] = df.utilib_counter.diff()

#Creating column for utilib 14 usage
df['utilib_14_usage'] = df.utilib_14_counter.diff()

In [13]:
df.head(10)

address  ...  utilib_14_usage
0                 2 Avenue de Suffren  ...              NaN
1           145 Rue Raymond Losserand  ...              0.0
2    2 Avenue John Fitzgerald Kennedy  ...              2.0
3              51 Rue Eugène Oudiné  ...             -2.0
4  6 avenue de la Porte de Champerret  ...              0.0
5                8 Boulevard Voltaire  ...              0.0
6                      37 rue Leblanc  ...              0.0
7         17 Rue des Luaps Prolongée  ...              0.0
8               34 avenue Jean Moulin  ...              0.0
9        41 boulevard de Rochechouart  ...              0.0

[10 rows x 19 columns]

# Challanges

# Bluecar

In [14]:
#+ve number means that a car was returned, -ve number means that a car was picked 
#0 means that nothing happened, i.e no car was picked nor returned
df.bluecar_usage.unique()

array([nan,  6., -3.,  0.,  3., -2.,  5., -6.,  1.,  4., -5., -1.,  2.,
       -4.,  7., -7.])

In [27]:
#Identify the most popular hour of the day for picking up a shared electric car (Bluecar) 
#in the city of Paris over the month of April 2018.
df[(df.city == 'Paris') & (df.bluecar_usage ==-7 )].groupby('hour')['hour'].count().sort_values(ascending = False).head(1)

hour
14    1
Name: hour, dtype: int64

The most popular hour of picking shared electric car (Blue car) was 2 pm

In [35]:
#What is the most popular hour for returning cars?
df[df.bluecar_usage >0 ].groupby('hour')['hour'].count().sort_values(ascending = False).head(1)

hour
6    101
Name: hour, dtype: int64

In [36]:
#What station is the most popular?
df[(df.bluecar_usage < 0) & (df.hour == 14)].groupby('postal_code').count()[['bluecar_usage']].sort_values(by = 'bluecar_usage', ascending = False).head(1)


bluecar_usage
postal_code               
75014                    6

In [37]:
#What postal code is the most popular for picking up Blue cars?
df[df.bluecar_usage < 0].groupby('postal_code').count()[['bluecar_usage']].sort_values(by = 'bluecar_usage', ascending = False).head(1)

#Does the most popular station belong to that postal code?
#It doesnt belong to the code

bluecar_usage
postal_code               
75015                  116

# Utilib

In [19]:
#+ve number means that a car was returned, -ve number means that a car was picked 
#0 means that nothing happened, i.e no car was picked nor returned
df.utilib_usage.unique()

array([nan,  0.,  1., -1.,  2., -2.])

In [31]:
#Identify the most popular hour of the day for picking up a shared electric car (Utilib) 
#in the city of Paris over the month of April 2018.
df[(df.city == 'Paris') & (df.utilib_usage ==-2)].groupby('hour')['hour'].count().sort_values(ascending = False).head(1)

hour
10    2
Name: hour, dtype: int64

In [32]:
#What is the most popular hour for returning cars?
df[df.utilib_usage == 2.].groupby('hour')['hour'].count().sort_values(ascending = False).head(1)

hour
8    3
Name: hour, dtype: int64

In [38]:
#What station is the most popular during the popular picking hour?
df[(df.utilib_usage < 0) & (df.hour == 8)].groupby('postal_code').count()[['utilib_usage']].sort_values(by = 'utilib_usage', ascending = False).head(1)


utilib_usage
postal_code              
75007                   2

# Utilib 1.4

In [23]:
#+ve number means that a car was returned, -ve number means that a car was picked 
#0 means that nothing happened, i.e no car was picked nor returned
df.utilib_14_usage.unique()

array([nan,  0.,  2., -2.,  1., -1.,  3., -3.])

In [24]:
#Identify the most popular hour of the day for picking up a shared electric car (Utilin 1.4) 
#in the city of Paris over the month of April 2018.
df[(df.city == 'Paris') & (df.utilib_14_usage == -3.0)].groupby('hour')['hour'].count().sort_values(ascending = False).head(1)

hour
2    1
Name: hour, dtype: int64

In [25]:
#What is the most popular hour for returning cars?
df[df.utilib_14_usage == 3.].groupby('hour')['hour'].count().sort_values(ascending = False).head(1)

hour
13    1
Name: hour, dtype: int64

The most popular hour for returning cars(utilib 1.4) is 13hrs which is 1pm

In [39]:
#What station is the most popular during the popular picking hour?
df[(df.utilib_14_usage < 0) & (df.hour == 13)].groupby('postal_code').count()[['utilib_14_usage']].sort_values(by = 'utilib_14_usage', ascending = False).head(1)


utilib_14_usage
postal_code                 
75014                      2